### ISSUE TITLE
While creating new solution it is showing error for incompatible python version even for supported python version 3.11.9

### ISSUE THREAD

**Issue by sudesh-palase-ansys** [ansys/ansys-templates#514]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

After installing ansys-templates, solution template is getting created but gives following error while setting up the environment:
```python
Traceback (most recent call last):
  File "D:\python_vscode_test\example-pyansys-app\setup_environment.py", line 1075, in <module>
    main()
  File "D:\python_vscode_test\example-pyansys-app\setup_environment.py", line 1010, in main
    check_inputs(args)
  File "D:\python_vscode_test\example-pyansys-app\setup_environment.py", line 339, in check_inputs
    check_python_version(args)
  File "D:\python_vscode_test\example-pyansys-app\setup_environment.py", line 276, in check_python_version
    raise Exception(f"Python version must be {lower_bound_symbol} {lower_version}.")
Exception: Python version must be >= 3.10.
```

### 📝 Steps to reproduce

Install ansys-template 4.0.0
Create new SAF solution using command: python setup_environment.py -d all -f

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
absl-py==1.2.0
annotated-types==0.6.0   
ansys-templates==4.0.0   
anyio==3.7.1
arrow==1.3.0
Aspose.Slides==21.11     
astunparse==1.6.3        
async-generator==1.10    
atomicwrites==1.4.0      
attrs==21.2.0
Automat==20.2.0
binaryornot==0.4.4       
Brotli==1.0.9
cachetools==5.2.0        
certifi==2021.5.30       
cffi==1.14.6
chardet==5.2.0
charset-normalizer==2.0.6
click==8.0.3
cloudpickle==2.0.0       
colorama==0.4.4
ConfigArgParse==1.5.3    
configparser==5.2.0      
constantly==15.1.0       
cookiecutter==2.2.3      
coverage==6.2
coveralls==3.3.1
cryptography==3.4.8      
cycler==0.11.0
decorator==5.1.1
docopt==0.6.2
et-xmlfile==1.1.0
exceptiongroup==1.1.3
fastapi==0.103.2
Flask==2.2.3
Flask-BasicAuth==0.2.0
Flask-Cors==3.0.10
flatbuffers==1.12
future==0.18.2
gast==0.4.0
genson==1.2.2
gevent==22.10.2
geventhttpclient==2.0.8
google-auth==2.11.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
greenlet==2.0.2
grpcio==1.47.0
h11==0.12.0
h5py==3.7.0
hyperlink==21.0.0
hypothesis==6.35.0
idna==3.2
importlib-metadata==4.12.0
imutils==0.5.4
incremental==21.3.0
iniconfig==1.1.1
isort==5.13.2
itsdangerous==2.1.2
Jinja2==3.1.2
joblib==1.1.0
jsonpath-ng==1.5.3
jsonschema==4.4.0
keras==2.9.0
Keras-Preprocessing==1.1.2
kiwisolver==1.3.2
libclang==14.0.6
locust==2.15.0
lxml==4.7.1
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.4.3
mock==4.0.3
MouseInfo==0.1.3
msgpack==1.0.4
nltk==3.6.7
numpy==1.21.1
oauthlib==3.2.0
opencv-python==4.5.3.56
openpyxl==3.0.7
opt-einsum==3.3.0
outcome==1.1.0
packaging==21.3
pandas==1.3.1
patsy==0.5.1
Pillow==8.3.1
plotly==5.3.1
plotly-express==0.4.1
pluggy==1.0.0
ply==3.11
protobuf==3.19.4
psutil==5.9.4
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAutoGUI==0.9.53
pycparser==2.20
pydantic==2.4.2
pydantic_core==2.10.1
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pyOpenSSL==20.0.1
pyparsing==3.0.6
pyperclip==1.8.2
PyRect==0.1.4
pyrsistent==0.18.1
PyScreeze==0.1.27
pytest==6.2.5
pytest-cov==3.0.0
python-dateutil==2.8.2
python-pptx==0.6.21
python-slugify==8.0.4
PyTweening==1.0.3
pytz==2021.1
pywin32==305
PyYAML==6.0.2
pyzmq==25.0.0
regex==2021.11.10
requests==2.26.0
requests-oauthlib==1.3.1
roundrobin==0.0.4
rsa==4.9
scikit-learn==1.0.2
scipy==1.7.0
selenium==4.0.0rc1
simplejson==3.17.6
six==1.16.0
sklearn==0.0
sniffio==1.2.0
sortedcontainers==2.4.0
starlette==0.27.0
statsmodels==0.12.2
tabpy==2.4.0
tenacity==8.0.1
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.9.1
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.26.0
termcolor==1.1.0
text-unidecode==1.3
textblob==0.17.1
threadpoolctl==3.0.0
toml==0.10.2
tomli==2.0.0
tornado==6.1
touch==2020.12.3
tqdm==4.62.3
trio==0.19.0
trio-websocket==0.9.2
Twisted==21.7.0
twisted-iocpsupport==1.0.2
types-python-dateutil==2.9.0.20241003
typing_extensions==4.8.0
urllib3==1.26.7
uvicorn==0.23.2
values==2020.12.3
Werkzeug==2.2.2
wrapt==1.14.1
wsproto==1.0.0
XlsxWriter==3.0.2
zipp==3.8.1
zope.event==4.6
zope.interface==5.4.0
```

**Comment by romainlejeune** [comment]
@JoseRamonRodriguez @iazehaf 

Here it says that python Python 3.9 to 3.10 are supported. https://github.com/ansys/ansys-templates/tree/demo/solution?tab=readme-ov-file#prerequisites

So either the doc is wrong and we have an issue, either the error message sent to Sudesh is wrong: "Python version must be >= 3.10.".
Or I'm missing something...

**Comment by JoseRamonRodriguez** [comment]
@romainlejeune you are correct, it should be from 3.10. @iazehaf can you guys please correct it?

**Comment by iazehaf** [comment]
@romainlejeune  and @JoseRamonRodriguez this is not a bug. The solution template in ``ansys-templates`` 4.0.0 only supports python 3.10 because it uses ``saf-desktop`` 1.2.1 which only supports python 3.10.  Latest ``saf-desktop`` releases support beyond 3.10 but the solution template has not been updated yet. In the next release, we will upgrade ``saf-desktop`` and extend the supported python version.

**Comment by romainlejeune** [comment]
Thanks @iazehaf 
So python 3.11 is not supported indeed, and the problem is the error message: 
`Exception: Python version must be >= 3.10.`
as it is the case when using 3.11... I would expect:
`Exception: Python version must be <= 3.10.`

**Comment by iazehaf** [comment]
@romainlejeune yes that part is under investigation. Will provide a fix ASAP.
